require:
  - rubocop-github-annotation-formatter
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"
  TargetRubyVersion: 3.1

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Lint/SymbolConversion:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods:
    - "class_methods"
    - "concerning"
  Exclude:
    - "config/routes.rb"

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/IfUnlessModifier:
  Enabled: false

Style/InfiniteLoop:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/Lambda:
  EnforcedStyle: literal

Style/Next:
  MinBodyLength: 5

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Rails/BulkChangeTable:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/Output:
  Exclude:
    - db/*.rb

RSpec/ExampleLength:
  Max: 20

RSpec/NoExpectationExample:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5
