require:
  - rubocop-erb
  - rubocop-factory_bot
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  CacheRootDirectory: tmp/cache

FactoryBot/AssociationStyle:
  EnforcedStyle: explicit

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/SymbolConversion:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods:
    - class_methods
    - concerning
    - describe
    - define
    - factory
    - FactoryBot.define
  Exclude:
    - config/routes.rb
    - test/factories/web/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/Lambda:
  EnforcedStyle: literal

Style/Next:
  MinBodyLength: 5

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Rails/OutputSafety:
  Enabled: false
