[tools]
node = "24"
"npm:typescript" = "7.0.2"
"npm:stylelint" = "17.16.0"
"npm:stylelint-config-standard" = "40.0.0"

python = "3.14"
yamllint = "1.38.0"

[tasks.lint]
description = "Run all linting tasks"
depends = ["lint:*"]

[tasks."lint:css"]
description = "Run stylelint"
run = "stylelint --config .github/.stylelintrc.json --config-basedir \"$(mise where npm:stylelint-config-standard)\" 'app/**/*.css'"

[tasks."lint:ts"]
description = "Run typescript (tsc)"
run = "tsc --noEmit -p .github/tsconfig.json"

[tasks."lint:yaml"]
description = "Run yamllint"
run = "yamllint -c .github/yamllint.yml -s ."
