name: Load Docker Image
description: Load Docker Image

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v5
      with:
        cache-from: type=gha
        load: true
        tags: reverser

    # It could be so easy. https://github.com/docker/compose/issues/7423
    - name: Set docker run command
      run: echo "DOCKER_RUN=echo -e \"CI=1\nREVERSER_DATA_PATH=${{ runner.temp }}/reverser\" > .env && docker compose run" >> "$GITHUB_ENV"
      shell: bash
