name: Load Docker Image
description: Load Docker Image

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v5
      with:
        cache-from: type=gha
        load: true
        tags: reverser:test

    - name: Set docker run command
      run: echo "DOCKER_RUN=docker compose run --rm -e RAILS_ENV=test -e CI=true" >> "$GITHUB_ENV"
      shell: bash
