name: Load Docker Image
description: Load Docker Image

runs:
  using: composite
  shell: bash
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: reverser-image
        path: /tmp
      
    - name: Load Docker image
      run: docker load --input /tmp/reverser-image.tar

    - name: Set docker run command
      run: echo "DOCKER_RUN=docker run --rm --network host -e POSTGRES_HOST=localhost -e RAILS_ENV=test -v $PWD:/app reverser:test" >> "$GITHUB_ENV"
