name: Docker Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

permissions:
  packages: write

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Generate Docker tags
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ghcr.io/earlopain/reverser
          tags: |
            type=sha,format=long,prefix=
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
          flavor: |
            latest=${{ github.ref == 'refs/heads/master' }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

          # cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          # cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max
          cache-from: type=gha
          cache-to: type=gha,mode=max
