name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Generate Docker tags
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ghcr.io/earlopain/reverser
          tags: |
            type=sha,format=long,prefix=
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
          flavor: |
            latest=${{ github.ref == 'refs/heads/master' }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: actions/checkout@v3

      - run: docker-compose pull ghcr.io/earlopain/reverser:${{ github.sha }}

      - uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Create DB
        run: docker-compose run --rm reverser bin/rails db:prepare

      - name: Run RSpec
        run: docker-compose run --rm rspec
