name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v3

      - run: docker-compose pull

      - uses: satackey/action-docker-layer-caching@v0.0.11

      - run: docker-compose up --build
  rspec:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: RSpec
      - run: docker-compose run --rm rspec
