name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11

      - run: docker-compose build

  rspec:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Create DB
        run: docker-compose run --rm reverser bin/rails db:prepare

      - name: RSpec
        run: docker-compose run --rm rspec
