name: Checks

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: reverser:test

  tests:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/prepare-docker-image

      - name: Run Tests
        run: docker compose run --rm -e REVERSER_DATA_PATH=dummy -e CI=true tests

  rubocop:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/prepare-docker-image

      - name: Run Rubocop
        run: $DOCKER_RUN rubocop --format github

  yamllint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: >
          pip install yamllint==1.32.0 &&
          yamllint -c .github/yamllint.yml -s .
