name: Load Docker Image
description: Load Docker Image

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: reverser-image
        path: /tmp
      
    - name: Load Docker image
      run: docker load --input /tmp/reverser-image.tar

    - uses: actions/checkout@v3
